### CascadeLang ###
# Cascade to Golang transformer
#
# Translates Cascade AST code into valid Go code
###################

import os
import re
import sys
from lark import Transformer, Visitor, Lark, Tree, Token
from sub.errorlib import showFastError

def get_base_dir():
    if getattr(sys, 'frozen', False):
        return os.path.dirname(os.path.abspath(sys.executable))
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BASE_DIR = get_base_dir()

def clean_lib_name(val):
    if val is None:
        return ""
    if isinstance(val, Tree):
        if val.children:
            return clean_lib_name(val.children[0])
        return ""
    s = str(val)
    cleaned = re.sub(r'[<>"\'\s:]', '', s)
    return cleaned


class TypeChecker(Visitor):
    def __init__(self):
        super().__init__()
        self.libraries_imported = set()

    def check(self, tree):
        self.libraries_imported.clear()
        
        for node in tree.find_data('use_stmt'):
            if node.children:
                lib = clean_lib_name(node.children[0])
                if lib:
                    self.libraries_imported.add(lib)
        
        for node in tree.find_data('fn_stmt'):
            if node.children:
                lib_name = clean_lib_name(node.children[0])
                if lib_name and lib_name not in self.libraries_imported:
                    showFastError(
                        "Import", 
                        f"Library '{lib_name}' is not imported! Use 'use <{lib_name}>'", 
                        f"Add 'use <{lib_name}>'"
                    )
                    raise Exception(f"Library '{lib_name}' not imported")


class TypeErrorException(Exception):
    pass


class GoTransformer(Transformer):

    def __init__(self, visit_tokens=True):
        super().__init__(visit_tokens)
        self.libraries_imported = set()
        self.user_functions = []
        self.public_functions = []
        self.public_compiled_code = []
        self.pre_calls = []
        self.imports = set(["fmt"])
        self.need_funcs = ""
        self.included_files = set()
        self.loop_counter = 0

    def transform(self, tree):
        self.libraries_imported.clear()
        for node in tree.find_data('use_stmt'):
            if node.children:
                lib = clean_lib_name(node.children[0])
                if lib:
                    self.libraries_imported.add(lib)

        return super().transform(tree)

    def start(self, instructions):
        filtered_instructions = []
        
        for pre_call in self.pre_calls:
            filtered_instructions.append(pre_call)

        for inst in instructions:
            if inst is None:
                continue
            if isinstance(inst, dict) and inst.get("is_call"):
                line = inst["code"]
            else:
                line = str(inst).strip()

            if line:
                filtered_instructions.append(line)

        imports_block = ""
        if self.imports:
            imp_list = [f'\t"{imp}"' for imp in sorted(self.imports)]
            imports_block = "import (\n" + "\n".join(imp_list) + "\n)\n\n"

        main_body = "\n".join(f"\t{line}" for line in filtered_instructions)
        main_func = f"func main() {{\n{main_body}\n}}"

        funcs_block = "\n\n".join(self.user_functions)
        if funcs_block:
            funcs_block = "\n\n" + funcs_block

        header = "// Code generated by Cascade Compiler\npackage main\n\n"
        return header + imports_block + self.need_funcs + main_func + funcs_block

    def _map_type(self, t):
        t = str(t).strip()
        if t in ("int", "num"):
            return "int"
        if t == "float":
            return "float64"
        if t == "str":
            return "string"
        if t == "arr":
            return "[]interface{}"
        if t == "bool":
            return "bool"
        return "interface{}"
    
    def _unwrap(self, val):
        if isinstance(val, dict) and val.get("is_call"):
            return val["code"]
        return str(val) if val is not None else ""

    def assignment(self, args):
        var_name = str(args[0]).strip()
        var_type = str(args[1]).strip()
        value = args[2]

        go_type = self._map_type(var_type)

        if isinstance(value, dict) and value.get("is_call"):
            call_code = value["code"]
            return f"var {var_name} {go_type} = {call_code}"

        raw_val = str(value).strip() if value is not None else '""'

        if var_type == "inp":
            self.imports.add("bufio")
            self.imports.add("os")
            self.imports.add("strings")
            prompt = raw_val if raw_val else '""'
            return f'fmt.Print({prompt})\n\treader_{var_name} := bufio.NewReader(os.Stdin)\n\t{var_name}_raw, _ := reader_{var_name}.ReadString(\'\\n\')\n\tvar {var_name} string = strings.TrimSpace({var_name}_raw)'

        return f"var {var_name} {go_type} = {raw_val}"

    def array_elements(self, args):
        return [str(arg).strip() for arg in args if arg is not None]

    def array_literal(self, args):
        if not args or args[0] is None:
            return []
        return args[0] if isinstance(args[0], list) else [args[0]]

    def array_init_assignment(self, args):
        var_name = str(args[0]).strip()
        var_type = str(args[1]).strip()
        elements = args[2] if isinstance(args[2], list) else []

        go_type = self._map_type(var_type)
        elems_str = ", ".join(str(e).strip() for e in elements)
        return f"var {var_name} = {go_type}{{{elems_str}}}"

    def array_element_assignment(self, args):
        var_name = str(args[0]).strip()
        idx = str(args[1]).strip()
        value = str(args[3]).strip()
        return f"{var_name}[{idx}] = {value}"

    def array_access(self, args):
        array_name = str(args[0]).strip()
        idx = str(args[1]).strip()
        return f"{array_name}[{idx}]"

    def print_stmt(self, args):
        arg = args[0]
        if arg is None or str(arg).strip() == "":
            return "fmt.Println()"
        return f"fmt.Println({str(arg).strip()})"
    
    def break_stmt(self, args):
        return f"break"
    
    def mut_stmt(self, args):
        variable_name = str(args[0])
        new_value = str(args[1])
        if variable_name is None or new_value is None:
            showFastError("Variable", "Mutated invalid variable", "Check variable or value")
            return ""
        return f"{variable_name} = {new_value}"

    def return_stmt(self, args):
        if not args or args[0] is None:
            return "return"
        return f"return {str(args[0]).strip()}"

    def type(self, args):
        return str(args[0])

    def str_val(self, args):
        s = str(args[0])
        if not (s.startswith('"') and s.endswith('"')):
            return f'"{s}"'
        return s

    def expression(self, args):
        return args[0]

    def term(self, args):
        return args[0]

    def factor(self, args):
        return args[0]

    def bracket_expr(self, args):
        return f"({args[0]})"

    def num(self, args):
        return str(args[0])

    def var(self, args):
        return str(args[0])

    def argument(self, args):
        return self._unwrap(args[0])

    def arguments(self, args):
        return [self._unwrap(arg) for arg in args if arg is not None]
    
    def incr_stmt(self, args):
        var_name = str(args[0]).strip()
        op = str(args[1]).strip()
        
        if op == "+":
            return f"{var_name}++"
        elif op == "-":
            return f"{var_name}--"
            
        return f"ARGUMENTS: {var_name}, {op}"

    def use_stmt(self, args):
        libname = clean_lib_name(args[0])
        if libname:
            self.libraries_imported.add(libname)
        return ""

    def fn_stmt(self, args):
        lib_name = clean_lib_name(args[0])
        func_name = str(args[1]).strip() if len(args) > 1 else ""
        raw_args = args[2] if len(args) > 2 else []

        if lib_name and lib_name not in self.libraries_imported:
            showFastError("Import", f"Library '{lib_name}' is not imported! Use 'use <{lib_name}>'", f"Add 'use <{lib_name}>'")
            raise Exception(f"Library '{lib_name}' not imported")

        if isinstance(raw_args, list):
            arguments_list = raw_args
        elif raw_args is None:
            arguments_list = []
        else:
            arguments_list = [raw_args]

        res = self._handle_std_lib_call(lib_name, func_name, arguments_list)
        return {"is_call": True, "code": res}

    def _handle_std_lib_call(self, lib_name, func_name, args):
        clean_args = [str(a).strip() for a in args if str(a).strip()]

        if lib_name == "std":
            self.imports.add("os")
            self.imports.add("os/exec")
            if func_name == "echo":
                msg = " ".join(clean_args) if clean_args else ""
                return f'cmd := exec.Command("cmd", "/c", "echo " + fmt.Sprint({msg})); cmd.Stdout = os.Stdout; cmd.Run()'
            if func_name == "pause":
                return 'cmd := exec.Command("cmd", "/c", "pause"); cmd.Stdout = os.Stdout; cmd.Stdin = os.Stdin; cmd.Run()'

            cmd_args = ", ".join(clean_args)
            if cmd_args:
                return f'cmd := exec.Command("cmd", "/c", "{func_name}", fmt.Sprint({cmd_args})); cmd.Stdout = os.Stdout; cmd.Run()'
            return f'cmd := exec.Command("cmd", "/c", "{func_name}"); cmd.Stdout = os.Stdout; cmd.Run()'

        if lib_name == "env":
            self.imports.add("os")
            self.imports.add("os/exec")

            if func_name == "clear":
                return 'cmd := exec.Command("cmd", "/c", "cls"); cmd.Stdout = os.Stdout; cmd.Run()'
            if func_name == "pause":
                return 'cmd := exec.Command("cmd", "/c", "pause"); cmd.Stdout = os.Stdout; cmd.Stdin = os.Stdin; cmd.Run()'
            if func_name == "title":
                title_val = clean_args[0] if clean_args else '""'
                return f'cmd := exec.Command("cmd", "/c", "title " + fmt.Sprint({title_val})); cmd.Run()'
            if func_name == "color":
                color_val = clean_args[0] if clean_args else '""'
                return f'cmd := exec.Command("cmd", "/c", "color " + fmt.Sprint({color_val})); cmd.Stdout = os.Stdout; cmd.Run()'
            if func_name == "quit":
                return "os.Exit(0)"
            if func_name == "consize":
                cols = clean_args[0] if len(clean_args) > 0 else "80"
                lines = clean_args[1] if len(clean_args) > 1 else "25"
                return f'cmd := exec.Command("cmd", "/c", fmt.Sprintf("mode con: cols=%v lines=%v", {cols}, {lines})); cmd.Stdout = os.Stdout; cmd.Run()'
            if func_name == "waypoint":
                label_val = clean_args[0].strip('"\'') if clean_args else ""
                return f"{label_val}:"
            if func_name == "goto":
                label_val = clean_args[0].strip('"\'') if clean_args else ""
                return f"goto {label_val}"

        if lib_name == "string":
            self.imports.add("strings")
            if func_name == "len":
                return f"len({clean_args[0]})"
            if func_name == "upper":
                return f"strings.ToUpper({clean_args[0]})"
            if func_name == "lower":
                return f"strings.ToLower({clean_args[0]})"
            if func_name == "trim":
                return f"strings.TrimSpace({clean_args[0]})"
            if func_name == "contains":
                return f"strings.Contains({clean_args[0]}, {clean_args[1]})"

        if lib_name == "arr":
            if func_name == "append":
                return f"{clean_args[0]} = append({clean_args[0]}, {clean_args[1]})"
            if func_name == "len":
                return f"len({clean_args[0]})"
            
        if lib_name == "random":
            self.imports.add("math/rand")
            if func_name == "getint":
                return f"rand.Intn({clean_args[1]} - {clean_args[0]} + 1) + {clean_args[0]} "
            if func_name == "getfloat":
                return f"{clean_args[0]} + rand.Float64()*({clean_args[1]} - {clean_args[0]})"
        
        if lib_name == "file":
            self.imports.add("os")
            self.need_funcs += """
func must[T any](v T, err error) T {
    if err != nil {
        panic(err)
    }
    return v
}
func mustErr(err error) {
    if err != nil {
        panic(err)
    }
}\n
"""
            if func_name == "read":
                return f'string(must(os.ReadFile({clean_args[0]})))'
            if func_name == "write":
                return f'mustErr(os.WriteFile({clean_args[0]}, []byte({clean_args[1]}), 0644))'
            
        if lib_name == "math":
            self.imports.add("math")
            if func_name == "sqrt":
                return f'math.Sqrt({clean_args[0]})'
            if func_name == "sin":
                return f'math.Sin({clean_args[0]})'
            if func_name == "cos":
                return f'math.Cos({clean_args[0]})'
            if func_name == "pi":
                return 'math.Pi'
            if func_name == "e":
                return 'math.E'
            if func_name == "phi":
                return 'math.Phi'
            
        if lib_name == "time":
            self.imports.add("time")
            if func_name == "timeout":
                return f'time.Sleep(time.Duration({clean_args[0]}) * time.Millisecond)'
            if func_name == "now":
                return "time.Now()"
            elif func_name == "date":
                return "time.Now().Format(\"2006-01-02\")"           
            elif func_name == "time":
                return "time.Now().Format(\"15:04:05\")"            
            elif func_name == "datetime":
                return "time.Now().Format(\"2006-01-02 15:04:05\")"           
            elif func_name == "timestamp":
                return "time.Now().Unix()"            
            elif func_name == "timestamp_nano":
                return "time.Now().UnixNano()"            
            elif func_name == "year":
                return "time.Now().Year()"            
            elif func_name == "month":
                return "time.Now().Month()"  
            elif func_name == "day":
                return "time.Now().Day()"          
            elif func_name == "hour":
                return "time.Now().Hour()"          
            elif func_name == "minute":
                return "time.Now().Minute()"          
            elif func_name == "second":
                return "time.Now().Second()"           
            elif func_name == "weekday":
                return "time.Now().Weekday()"            
            elif func_name == "yearday":
                return "time.Now().YearDay()"
            
        if lib_name == "psgraph":
            if func_name == "gotoxy":
                x = clean_args[0] if len(clean_args) > 0 else "0"
                y = clean_args[1] if len(clean_args) > 1 else "0"
                return f'fmt.Printf("\\033[%d;%dH", {y}+1, {x}+1)'
            if func_name == "clear":
                return 'fmt.Print("\\033[2J\\033[H")'
            if func_name == "hide_cursor":
                return 'fmt.Print("\\033[?25l")'
            if func_name == "show_cursor":
                return 'fmt.Print("\\033[?25h")'
            
        if lib_name == "convert":
            return f'{func_name}({clean_args[0]})'

        args_str = ", ".join(clean_args)
        return f"{lib_name}.{func_name}({args_str})"
    
    def write_stmt(self, args):
        arg = args[0]
        if arg is None or str(arg).strip() == "":
            return ""
        return f"fmt.Print({self._unwrap(arg).strip()})"

    def call_stmt(self, args):
        fn_name = str(args[0])
        raw_args = args[1] if len(args) > 1 else []

        if isinstance(raw_args, list):
            arguments_list = raw_args
        elif raw_args is None:
            arguments_list = []
        else:
            arguments_list = [raw_args]

        args_str = ", ".join(str(a).strip() for a in arguments_list if str(a).strip())
        return {"is_call": True, "code": f"{fn_name}({args_str})"}

    def _extract_instruction_code(self, sub):
        if sub is None:
            return ""
        if isinstance(sub, dict) and sub.get("is_call"):
            return sub["code"]
        if isinstance(sub, list):
            lines = [self._extract_instruction_code(x) for x in sub]
            return "\n".join(line for line in lines if line)
        s = str(sub).strip()
        return s if s else ""

    def block(self, args):
        instructions = []
        for item in args:
            if isinstance(item, list):
                for sub in item:
                    code = self._extract_instruction_code(sub)
                    if code:
                        instructions.append(code)
            else:
                code = self._extract_instruction_code(item)
                if code:
                    instructions.append(code)
        return instructions

    def elseif_block(self, args):
        cond = args[0]
        body = args[1]
        return {"cond": cond, "body": body}

    def else_block(self, args):
        return args[0]

    def if_stmt(self, args):
        cond = args[0]
        body = args[1]
        elseifs = []
        else_body = None

        for arg in args[2:]:
            if isinstance(arg, dict) and "cond" in arg:
                elseifs.append(arg)
            elif isinstance(arg, list):
                else_body = arg

        indented_body = "\n".join(f"\t\t{line}" for line in body)
        res = f"if {cond} {{\n{indented_body}\n\t}}"

        for ei in elseifs:
            ei_body = "\n".join(f"\t\t{line}" for line in ei["body"])
            res += f" else if {ei['cond']} {{\n{ei_body}\n\t}}"

        if else_body is not None:
            e_body = "\n".join(f"\t\t{line}" for line in else_body)
            res += f" else {{\n{e_body}\n\t}}"

        return res

    def while_stmt(self, args):
        cond = args[0]
        body = args[1]
        indented_body = "\n".join(f"\t\t{line}" for line in body)
        return f"for {cond} {{\n{indented_body}\n\t}}"

    def for_num_stmt(self, args):
        var_name = str(args[0])
        start_val = args[1]
        end_val = args[2]

        if len(args) == 4 or args[3] is None:
            step_val = "1"
            body = args[3] if len(args) == 4 else args[4]
        else:
            step_val = str(args[3])
            body = args[4]

        indented_body = "\n".join(f"\t\t{line}" for line in body)
        return f"for {var_name} := {start_val}; {var_name} <= {end_val}; {var_name} += {step_val} {{\n{indented_body}\n\t}}"

    def foreach_stmt(self, args):
        var_name = str(args[0])
        target = str(args[1]).strip()
        body = args[2]
        indented_body = "\n".join(f"\t\t{line}" for line in body)
        return f"for _, {var_name} := range {target} {{\n{indented_body}\n\t}}"

    def walk_stmt(self, args):
        self.imports.add("os")
        self.imports.add("io/fs")
        self.imports.add("path/filepath")

        var_name = str(args[0]).strip()
        path = str(args[1]).strip()
        mask = str(args[2]).strip().replace('"', '').replace("'", "")
        body = args[3]

        indented_body = "\n".join(f"\t\t\t{line}" for line in body)

        return f'filepath.WalkDir({path}, func({var_name} string, d fs.DirEntry, err error) error {{\n\tif err != nil || d.IsDir() {{\n\t\treturn nil\n\t}}\n\tif matched, _ := filepath.Match("{mask}", filepath.Base({var_name})); matched {{\n{indented_body}\n\t}}\n\treturn nil\n}})'

    def readline_stmt(self, args):
        self.imports.add("os")
        self.imports.add("bufio")

        var_name = str(args[0]).strip()
        target = str(args[1]).strip()
        body = args[2]

        self.loop_counter += 1
        file_var = f"file_{self.loop_counter}"
        scanner_var = f"scanner_{self.loop_counter}"

        indented_body = "\n".join(f"\t\t{line}" for line in body)

        return f'{file_var}, err_{self.loop_counter} := os.Open({target})\n\tif err_{self.loop_counter} == nil {{\n\t\tdefer {file_var}.Close()\n\t\t{scanner_var} := bufio.NewScanner({file_var})\n\t\tfor {scanner_var}.Scan() {{\n\t\t\t{var_name} := {scanner_var}.Text()\n{indented_body}\n\t\t}}\n\t}}'

    def get_exports(self):
        return {
            "functions": self.public_functions,
            "code": "\n\n".join(self.public_compiled_code)
        }

    def fn_modifiers(self, args):
        return [str(m) for m in args if m is not None]

    def fn_decl(self, args):
        idx = 0
        modifiers = []
        if idx < len(args):
            first = args[idx]
            if isinstance(first, list):
                modifiers = [str(m) for m in first if m is not None]
                idx += 1
            elif hasattr(first, 'data') and first.data == 'fn_modifiers':
                modifiers = [str(m) for m in first.children if m is not None]
                idx += 1

        fn_name = str(args[idx]).strip()
        idx += 1

        fn_params = []
        if idx < len(args):
            curr = args[idx]
            if isinstance(curr, list):
                fn_params = curr
                idx += 1
            elif hasattr(curr, 'data') and curr.data == 'params':
                fn_params = [str(p.children[0]) for p in curr.children if hasattr(p, 'children')]
                idx += 1

        ret_type = ""
        if idx < len(args) and isinstance(args[idx], str) and args[idx] not in ("{", "}"):
            ret_type = f" {self._map_type(args[idx])}"
            idx += 1

        body_items = args[idx:]
        body_instructions = []
        for item in body_items:
            code = self._extract_instruction_code(item)
            if code:
                body_instructions.append(code)

        formatted_params = []
        for p in fn_params:
            parts = str(p).split(":")
            p_name = parts[0].strip()
            p_type = self._map_type(parts[1].strip()) if len(parts) > 1 else "interface{}"
            formatted_params.append(f"{p_name} {p_type}")

        params_str = ", ".join(formatted_params)
        body_str = "\n".join(f"\t{line}" for line in body_instructions)

        fn_code = f"func {fn_name}({params_str}){ret_type} {{\n{body_str}\n}}"
        self.user_functions.append(fn_code)

        if "pre" in modifiers:
            dummy_args = ", ".join('""' for _ in fn_params)
            self.pre_calls.append(f"{fn_name}({dummy_args})")

        if "pub" in modifiers:
            self.public_functions.append(fn_name)
            self.public_compiled_code.append(fn_code)

        return ""

    def include_stmt(self, args):
        raw_path = str(args[0]).strip('"\'')
        abs_path = os.path.abspath(raw_path)

        if abs_path in self.included_files:
            return ""

        if not os.path.exists(abs_path):
            raise FileNotFoundError(f"Included file not found: {raw_path}")

        self.included_files.add(abs_path)

        with open(abs_path, "r", encoding="utf-8") as f:
            included_code = f.read()

        included_ast = parser.parse(included_code)
        lib_transformer = GoTransformer()

        lib_transformer.included_files = self.included_files
        lib_transformer.transform(included_ast)

        for pub_code in lib_transformer.public_compiled_code:
            if pub_code not in self.user_functions:
                self.user_functions.append(pub_code)

        self.public_functions.extend(lib_transformer.public_functions)
        self.included_files.update(lib_transformer.included_files)
        self.imports.update(lib_transformer.imports)

        return ""

    def waypoint_stmt(self, args):
        label = args[0].strip('"\'')
        return f"{label}:"

    def goto_stmt(self, args):
        label = args[0].strip('"\'')
        return f"goto {label}"

    def eq(self, args): return f"{self._unwrap(args[0])} == {self._unwrap(args[1])}"
    def neq(self, args): return f"{self._unwrap(args[0])} != {self._unwrap(args[1])}"
    def lt(self, args): return f"{self._unwrap(args[0])} < {self._unwrap(args[1])}"
    def lte(self, args): return f"{self._unwrap(args[0])} <= {self._unwrap(args[1])}"
    def gt(self, args): return f"{self._unwrap(args[0])} > {self._unwrap(args[1])}"
    def gte(self, args): return f"{self._unwrap(args[0])} >= {self._unwrap(args[1])}"

    def add(self, args): return f"{self._unwrap(args[0])} + {self._unwrap(args[1])}"
    def minus(self, args): return f"{self._unwrap(args[0])} - {self._unwrap(args[1])}"
    def mul(self, args): return f"{self._unwrap(args[0])} * {self._unwrap(args[1])}"
    def div(self, args): return f"{self._unwrap(args[0])} / {self._unwrap(args[1])}"
    def mod(self, args): return f"{self._unwrap(args[0])} % {self._unwrap(args[1])}"

    def param(self, args): return f"{args[0]}:{args[1]}"
    def params(self, args): return [str(a) for a in args if a is not None]


grammar_path = os.path.join(BASE_DIR, "sub", "grammar.lark")
with open(grammar_path, 'r', encoding='utf-8') as f:
    my_grammar = f.read()

parser = Lark(my_grammar, parser='lalr')

def translatecode(code):
    try:
        ast_tree = parser.parse(code)
        
        checker = TypeChecker()
        checker.check(ast_tree) 

        transformer = GoTransformer()
        resulting_go = transformer.transform(ast_tree)
        return resulting_go

    except TypeErrorException as te:
        showFastError("Type", te, "Check types")
        return ""
    except Exception as e:
        if "not imported" not in str(e):
            showFastError("Syntax", e, "...")
        return ""